language: cpp

compiler:
    - gcc

dist: trusty
sudo: require

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - cppcheck
            - cmake

before_install:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++

# Build steps
script:
    - gcc -v && g++ -v
    - mkdir build_test
    - cd build_test
    - cmake .. -DCMAKE_BUILD_TYPE=Tests && make
    - ./Tests
    - cd ..
    - mkdir build
    - cd build
    - cmake .. && make
    - ./Raytracer
    - cppcheck --quiet --error-exitcode=1 .
    - gprof ./Raytracer > gprof.log
    - head gprof.log -n 100
