language: cpp

compiler:
    - gcc

dist: trusty
sudo: require

addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cppcheck
            - cmake

before_install:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++

# Build steps
script:
    - gcc -v && g++ -v
    - mkdir build_test
    - cd build_test
    - ${DEPS_DIR}/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Tests && make
    - ./Tests
    - cd ..
    - mkdir build
    - cd build
    - ${DEPS_DIR}/cmake/bin/cmake .. && make
    - ./Raytracer
    - cppcheck --quiet --error-exitcode=1 .
